function(earth_ensure_opencv_components)
    foreach(component IN LISTS ARGN)
        set(qualified_target "OpenCV::opencv_${component}")
        if(TARGET ${qualified_target})
            continue()
        endif()

        set(raw_target "opencv_${component}")
        if(TARGET ${raw_target})
            add_library(${qualified_target} INTERFACE IMPORTED)
            target_link_libraries(${qualified_target} INTERFACE ${raw_target})
        else()
            message(WARNING "未能为 OpenCV 组件 ${component} 创建命名空间目标，CMake 将回退到裸库名。")
        endif()
    endforeach()
endfunction()

function(earth_register_osg_component component_name)
    string(TOUPPER "${component_name}" upper_name)
    set(imported_target "OpenSceneGraph::${component_name}")
    if(TARGET ${imported_target})
        return()
    endif()

    set(library_release "${${upper_name}_LIBRARY_RELEASE}")
    set(library_debug "${${upper_name}_LIBRARY_DEBUG}")
    set(library_single "${${upper_name}_LIBRARY}")

    if(NOT library_release AND NOT library_debug AND library_single)
        set(library_release "${library_single}")
    endif()

    set(has_release FALSE)
    if(library_release AND NOT library_release MATCHES "-NOTFOUND")
        set(has_release TRUE)
    endif()

    set(has_debug FALSE)
    if(library_debug AND NOT library_debug MATCHES "-NOTFOUND")
        set(has_debug TRUE)
    endif()

    if(NOT has_release AND NOT has_debug)
        message(WARNING "缺少 OpenSceneGraph 组件 ${component_name} 的库路径，无法创建 IMPORTED 目标。")
        return()
    endif()

    add_library(${imported_target} UNKNOWN IMPORTED)

    if(has_release)
        set_property(TARGET ${imported_target} APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
        set_property(TARGET ${imported_target} PROPERTY IMPORTED_LOCATION_RELEASE "${library_release}")
    endif()

    if(has_debug)
        set_property(TARGET ${imported_target} APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
        set_property(TARGET ${imported_target} PROPERTY IMPORTED_LOCATION_DEBUG "${library_debug}")
    endif()

    set(fallback_config "")
    if(has_release)
        set(fallback_config Release)
    elseif(has_debug)
        set(fallback_config Debug)
    endif()

    if(fallback_config)
        foreach(extra_cfg RELWITHDEBINFO MINSIZEREL)
            set_property(TARGET ${imported_target} PROPERTY "MAP_IMPORTED_CONFIG_${extra_cfg}" "${fallback_config}")
        endforeach()
    endif()

    set(include_var "${upper_name}_INCLUDE_DIR")
    if(DEFINED ${include_var})
        set(include_dir "${${include_var}}")
        if(include_dir)
            set_target_properties(${imported_target} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${include_dir}")
        endif()
    endif()
endfunction()

function(earth_ensure_osg_components)
    foreach(component_name IN LISTS ARGN)
        earth_register_osg_component("${component_name}")
    endforeach()
endfunction()
